### ISSUE TITLE
Text box in docs

### ISSUE THREAD

**Issue by taiki-e** [trillium-rs/async-tls-acceptor#1]
The following `<Input>` is rendered as a text box.

https://github.com/trillium-rs/async-tls-acceptor/blob/4bf989b4d6ac3fdd5ba0842d98ca087f909ad4b7/src/lib.rs#L43

<img width="742" alt="ss" src="https://user-images.githubusercontent.com/43724913/116769967-0bc39b00-aa7b-11eb-9f32-1dab9930374a.png">

https://docs.rs/async-tls-acceptor/0.1.0/async_tls_acceptor/trait.Acceptor.html#associatedtype.Output

**Comment by jbr** [comment]
Thanks!
